# Data paths
data:
  train_data: "data/train.csv"
  test_data: "data/test.csv"
  prediction_path: "data/pred.csv"
  separator : ","
  target : "SalePrice"

# List of feature engineering processes to run
feature_engineering:
    - BucketizeTargetEncode
    - FeatureBucketize
    - TargetEncode

num_folds: 5

# Hyperparameter space to do model fune tuning in. (Grid search)
hyperparameters:

  objective: regression
  boosting: gbdt
  metric: mae
  verbosity: -1
  learning_rate:
    - 0.01
    - 0.1
    - 1.0
  max_depth:
    - 5
    # - 50
  min_child_weight:
    - 5
    # - 10